### ISSUE TITLE
Can you make info focusable?

### ISSUE THREAD

**Issue by aarongustafson** [JanPokorny/rotating10k#1]
`tabindex="0"` will make it possible.

**Comment by JanPokorny** [comment]
That makes it focusable, but it turns out tabbing to it and pressing Enter does nothing (`<label>`s just don't seem to work that way). I'll try restyling the corresponding `<input>` to overlay the label to mask that.

**Comment by JanPokorny** [comment]
Focusing, tabbing and keyboard navigation should work now.
